### ISSUE TITLE
RancherOS compatibility

### ISSUE THREAD

**Issue by jhmartin** [ampedandwired/rancher-reaper#4]
Labeling RancherOS nodes with dynamic values like instance-id at startup is tricky since the Rancher integration is not a shell command. Would it be possible to have a 'global service' Docker container that updates a node with the appropriate labels?

**Comment by ampedandwired** [comment]
If I understand you correctly, you want a container that:
1. runs in Rancher 
2. iterates over all Rancher hosts using the Rancher API
3. for each host finds the corresponding instances in AWS
4. applies the "aws.instance_id" and "aws.availability_zone" label to the Rancher host using the Rancher API

Is my understanding correct?

Assuming so, it's step (3) that's the tricky one. The information available about a host in Rancher is not quite enough to easily identify it in AWS. That's why I introduced those labels in the first place. If we could solve that, there would be no need to have a separate service, and no need to label hosts either.

I'll have another poke around the Rancher API to see what might be possible. I'm open to suggestions if you have any ideas.

**Comment by jhmartin** [comment]
2 and 3 aren't quite right. I am thinking of a container that runs as a 'global service' ie an instance of this container runs on every host. This way you can make use of the ec2-metadata service at 169.254.169.254 to fetch data about the instance you are on without having to have any ec2 credentials or know anything about where you are.
1. Fetch the local-hostname, instanceid and placement/availability_zone from the ec2 metadata service at 169.254.169.254 (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html)
2. Call the rancher API and find the host with the matching hostname
3. Apply the labels from #1.

If you label it as a 'agent' then it will automatically be spawned with variables for the config-url and credentials for rancher, so no hard-coding of either of these:
http://docs.rancher.com/rancher/v1.0/en/rancher-services/service-accounts/

If the container is scheduled as global service, no-restart then this will fire up once when a node provisions, mark the node, then exit and not take any additional resources.

**Comment by ampedandwired** [comment]
OK gotcha.

What you're suggesting sounds feasible. It's not really something I'm willing to take on though, as I'm not a RancherOS user and I don't have the time to invest in this right now. If you decide to tackle it I'll drop a mention in the README though to help out other users.

The ideal solution of course would be having RancherOS be able to use the ec2 metadata in cloud-init. Seems that you're not the first to come across this problem:
https://github.com/rancher/os/issues/1178
https://forums.rancher.com/t/getting-ec2-metadata-to-rancher-host-labels-on-rancheros/1467
https://forums.rancher.com/t/ec2-metadata-and-cloud-init/2975
